# Generated by Django 5.1.3 on 2024-11-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
